[package]
name = "solana-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = "2.1.13"
solana-sdk = "2.1.13"
serde_json = "1.0.138"
solana-transaction-status = "2.1.13"
log = "0.4.25"
spl-token = "7.0.0"
bincode = "1.3.3"
